### ISSUE TITLE
Bug: Strange layout appears when you click on base-css preview button

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#652] opened 2022-02-11 16:49 UTC
### Url where issue was found

[*Example: https://covid19.ca.gov/state-dashboard*](https://designsystem.webstandards.ca.gov/components/base-css/preview/)

### Operating system, device, browser, screen size, etc.

Chrome on iMac

### Steps to reproduce

1. Open componets
2. Click on base-css component
3. Click on preview

### Expected result

At least no overlays 

### Actual result

Statewide header (preview version of it) overlays with the side navigation

# Screen shot(s) or video capture
![Screen Shot 2022-02-11 at 8 44 32 AM](https://user-images.githubusercontent.com/31669748/153633260-2a910ebc-9104-4ee8-8014-09b1f41beb94.png)

**Comment by chachasikes** [comment] 2022-03-09 22:43
Is this still happening?

**Comment by aaronhans** [comment] 2022-03-10 16:56
Yes this is still a problem

Part of the cause: full-bleed is used in the statewide and sitewide header markup examples. This should be coming from template.html and that shouldn't include full-bleed as default so might have to modify those components. The full-bleed option should be explained separately and not included in default markup.

Other bugs to fix:
- There is also a 404 message in the middle of this page, review why that is happening
- The theme switcher isn't working. This was working in a previous release, research when the regression happenned, add playwright test to make sure it continues to work
- Seems like several of these components aren't dynamically grabbing the sample markup from the underlying components. Make sure this is working as expected

**Comment by aaronhans** [comment] 2022-03-16 23:17
Issues addressed in https://github.com/cagov/design-system/pull/747

**Comment by yesenia-gtz** [comment] 2022-03-23 18:53
Good to go!

**Comment by yesenia-gtz** [comment] 2022-03-23 18:57
Good to go!

**Closed** 2022-03-28 19:58 UTC
Labels: Bug, Engineering
