### ISSUE TITLE
Components page titles should not change when toggling Readme and Changelog tabs

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#606] opened 2022-02-02 20:42 UTC
[Sorry for the late addition, but I don't think this made it over from our QA spreadsheet]

In Figma mockups, the page title (e.g. Accordion) always stay the same regardless of the tab selected. Toggling a tab should not change the content above it. 

![image](https://user-images.githubusercontent.com/69167298/152234311-9040066e-a1ec-4ca1-a4a3-84cf9847ebc3.png)

![image](https://user-images.githubusercontent.com/69167298/152234277-dd2f2d33-511a-4728-8e97-ccbf128009d2.png)

On the live site, the title updates. This is not necessary but could the selected tab gives context to the content below it.

![image](https://user-images.githubusercontent.com/69167298/152234444-828bee1c-2ede-4d71-ae53-4c17aa106546.png)
![image](https://user-images.githubusercontent.com/69167298/152234514-ff5e1709-3da0-49e4-9cb6-b5f8443997a7.png)

**Comment by xjensen** [comment] 2022-02-15 22:59
We have a fix in progress for this at #665. 

Question. In the mock-ups, there's a short summary between the page title (component name) and the document tabs. 

> The accordion element allows for sections of text to be collapsed or expanded on click.

Should we add these short summaries onto each component page on the site? And if so, should we use existing content here, or do we want to draft new blurbs for each component? @adam-little @m-sullivan7

**Comment by m-sullivan7** [comment] 2022-02-16 00:08
Could I get a quick link to the mocks so I can see it in context?

**Comment by xjensen** [comment] 2022-02-16 00:23
Here's the [Figma mock-up](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=379%3A10012). 

And here's [an example page on the preview site](https://606-consistent-component-page-titles.pr.designsystem.webstandards.ca.gov/pr/606-consistent-component-page-titles/components/accordion/readme/). At this time, this preview site has the title fix, but not the blurb under discussion.

**Comment by m-sullivan7** [comment] 2022-02-16 00:28
Thank you! I was having trouble finding it.

I am happy with how it is now, below the tabs and trackerbox. I feel this content best fits below the tabs and the tracker boxes because it's part of the general readme info. It it was above the tabs, I'd expect it to be on the use case and changelog tabs. I do not think it's needed in those places.

I'm interested in the design perspective of @adam-little.

**Comment by adam-little** [comment] 2022-02-16 18:56
I also OK with summary being under tabs, since it only appears in the Readme tab. 

[#665](https://github.com/cagov/design-system/pull/665.) solves this for me.

I have a separate but related issue at [#607](https://github.com/cagov/design-system/issues/607) that I would like the perspective of @m-sullivan7 on.

I would argue that the Tracker Box should only appear on the Readme tab. Otherwise, it should be above the tabs.

**Comment by xjensen** [comment] 2022-02-16 23:27
That all makes sense. I added a question to #607. We could easily resolve #607 as part of this PR.

I'm going to keep this PR in draft-mode for a few days to see if we can get a decision on #607, otherwise I'll go ahead and push it forward.

**Comment by jaredwyee** [comment] 2022-02-23 22:23
Confirmed working. CLosing. Will move to Done once release is merged.

**Closed by jaredwyee** 2022-02-23 22:23 UTC
Labels: P2
