### ISSUE TITLE
General: Regulatory outline example needs to be shorter.

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#484] opened 2022-01-26 02:44 UTC
Please have non-eng review.

**Comment by zakiya** [comment] 2022-01-26 23:53
Duplicate of  #493 and $484

**Comment by m-sullivan7** [comment] 2022-02-02 18:03
@xjensen Another example of a demo that we can consider shortening.

**Comment by zakiya** [comment] 2022-02-02 18:13
@xjensen @m-sullivan7 I shortened this considerably  about a week ago. It could probably still be shorter but this is an example where the 4th level components down to at least (viii) are needed for proper testing because there's a risk of overlap with the margins.

**Comment by m-sullivan7** [comment] 2022-02-02 18:24
Ah! I hadn't done a hard refresh, so I was still seeing the old version. This is better.

I agree we need the fourth level in there. We might not need 9 fourth-level bullets though.

In looking now, we could also drop `LEVEL THREE` from the `(A)` bullet since we removed it from the other levels.

**Closed** 2022-07-12 16:44 UTC
