### ISSUE TITLE
Mail icon on state footer preview is huge

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#430] opened 2022-01-24 21:08 UTC
Seen on chrome on mac desktop

icon should be same size as other ones

**Comment by aaronhans** [comment] 2022-01-24 21:09
<img width="954" alt="Screen Shot 2022-01-24 at 1 08 49 PM" src="https://user-images.githubusercontent.com/353360/150865268-8874c1e9-c67d-4bcb-9cf5-d0cf77aa5300.png">

**Comment by xjensen** [comment] 2022-01-25 00:47
Looks like the SVG mark-up for the mail icon does not have a hard-coded `width` and `height` like the other icons.

**Comment by m-sullivan7** [comment] 2022-01-26 17:43
This appears to be a duplicate of https://github.com/cagov/design-system/issues/418. Flagging for whoever works on this.

**Closed** 2022-01-26 22:43 UTC
Labels: Component - footer, P1
