### ISSUE TITLE
iPhone: Regulatory outline example needs to be shorter and improve formatting

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#458] opened 2022-01-26 02:03 UTC
https://drive.google.com/file/d/1ntIvQ4syw-KbVTl5cW1GiaUNec95NB4g/view?usp=drivesdk

**Comment by zakiya** [comment] 2022-01-26 23:56
Duplicate of  #493 and #484. Closing.

**Closed by zakiya** 2022-01-26 23:56 UTC
Labels: P2, Component - regulatory-outline
