### ISSUE TITLE
Accordion page: shorten Use case title

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#519] opened 2022-01-26 03:42 UTC

**Comment by m-sullivan7** [comment] 2022-01-27 22:49
Is this as simple as updating the title of that `.md` file? If so, I'd be happy to make the change. Off the top of my head, I'd make the title _Accordion use cases_.

**Comment by m-sullivan7** [comment] 2022-02-02 22:46
@aaronhans Can I take this ticket? This looks pretty simple to do and I've got the time to tackle it. That allows you to do programming things that I can't. 🙂

**Comment by aaronhans** [comment] 2022-02-03 17:16
Yes please, thank you @m-sullivan7!

We may need to make content changes in this branch until it is merged due to the big movements in files and directory changes @xjensen just made https://github.com/cagov/design-system/tree/1.0.1-rc-post-launch-fixes

**Comment by aaronhans** [comment] 2022-02-03 17:17
This same problem may be present on other changelog pages on other components too

**Comment by m-sullivan7** [comment] 2022-02-03 17:56
Thanks! I coordinated with @xjensen and he said that I only need to work in https://github.com/cagov/design-system/tree/1.0.1-rc-post-launch-fixes if I'm working on documentation for one of the components listed in #602. Accordion is not one of those components, so I pushed this change directly in the `main` branch. I confirmed that this has published on production and am closing the issue.

**Closed by m-sullivan7** 2022-02-03 17:56 UTC
Labels: Component - accordion
